version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 8.26.1
    - 8.27.0
    - 8.28.1
    - 8.29.0
    - 8.31.0
    - 8.32.1
    - 8.33.1
    - 8.34.0
    - 8.35.1
    - 8.36.2
    - 8.37.0
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.18.3
    - 2.18.4
    - 2.18.5
  - dependency-name: psalm/plugin-laravel
    versions:
    - 1.4.3
  - dependency-name: orchestra/testbench
    versions:
    - 6.11.0
    - 6.12.1
    - 6.13.0
    - 6.15.0
    - 6.16.0
  - dependency-name: vimeo/psalm
    versions:
    - 4.5.2
    - 4.6.1
    - 4.6.2
    - 4.6.3
    - 4.6.4
    - 4.7.0
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.2
    - 9.5.3
